### ISSUE TITLE
Image quiz at Omega to learn new names

### ISSUE THREAD

**Issue by theodorklauritzen** [vevcom/projectNext#235]
Flip card or a quiz to easier learn names of people in your class.

**Comment by HaakonMikalsen** [comment]
**TODO Liste**

MVP:
- [ ] Flytte poeng scoren til et logisk sted
- [ ] Begrense antall navn (f.eks. hardkodet til 10, eller at brukeren kan justere)
- [ ] Navn markeres permanent grønt eller forsvinner (opp til deg!) når gjettet riktig
- [ ] Når alle navn er gjettet lages en ny liste med nye tilfeldige navn

Nice to haves:
- [ ] Lydeffekter
- [ ] Konfetti
- [ ] Tidgrense
- [ ] Velge hvilke personer som quizne skal inneholder
